### ISSUE TITLE
 jit_nodeValue_3(...).$any is not a function

### ISSUE THREAD

**Issue by smile2014** [formly-js/ngx-formly#661]
FormlyFieldInput.html:2 ERROR TypeError: jit_nodeValue_3(...).$any is not a function
    at Object.eval [as handleEvent] (FormlyFieldInput.html:2)
    at handleEvent (core.js:13581)
    at callWithDebugContext (core.js:15090)
    at Object.debugHandleEvent [as handleEvent] (core.js:14677)
    at dispatchEvent (core.js:9990)
    at eval (core.js:10611)
    at HTMLInputElement.eval (platform-browser.js:2628)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:424)

**Comment by aitboudad** [comment]
Hi, can you please provide a reproduction repo/example.

**Comment by smile2014** [comment]
thank you ,The problem has been solved, caused by carelessness

**Comment by snoop244** [comment]
Hi @smile2014 , what was the carelessness?  How did you fix this issue?  I have the exact same error, have updated Angular and Material and I still get that error on the console for every keystroke.  My model does not populate.  

Everything worked fine until I moved my project to another system and reinstalled packages.

**Comment by jdbranham** [comment]
I'm getting the same error, and I don't see any careless mistakes in my code =\  

I do notice that `self` is null in the below function [core.js]

```
/**
 * @param {?} action
 * @param {?} fn
 * @param {?} self
 * @param {?} args
 * @return {?}
 */
function callWithDebugContext(action, fn, self, args) {
    var /** @type {?} */ oldAction = _currentAction;
    var /** @type {?} */ oldView = _currentView;
    var /** @type {?} */ oldNodeIndex = _currentNodeIndex;
    try {
        _currentAction = action;
        var /** @type {?} */ result = fn.apply(self, args);
        _currentView = oldView;
        _currentNodeIndex = oldNodeIndex;
        _currentAction = oldAction;
        return result;
    }
    catch (/** @type {?} */ e) {
        if (isViewDebugError(e) || !_currentView) {
            throw e;
        }
        throw viewWrappedDebugError(e, /** @type {?} */ ((getCurrentDebugContext())));
    }
}
```

**Comment by Ubaid-ur-Rehman** [comment]
Hi,
I am getting the same error.
Can anyone help?
Thanks

**Comment by Ubaid-ur-Rehman** [comment]
@aitboudad  can you kindly help? Its urgent.
 thanks

**Comment by Ubaid-ur-Rehman** [comment]
@aitboudad  thanks it was resolved.
Although i've another problem.
I am uploading a JSON file and trying to bind it to the model property of the formly form but it's not showing the data in the form.
Can you kindly help me in this?
Thanks

**Comment by sandeep2701kumar** [comment]
Check the click function properly, you might give the function name and some variable name same. So, change the function name and weather solve or not.

**Comment by krawieeeec** [comment]
@sandeep2701kumar your answer resolve my issue, thanks :)

**Comment by GeoffMahugu** [comment]
@sandeep2701kumar had same name of my function as the template name, thanks 👍

**Comment by shanurrahman** [comment]
or maybe if you are using forms, just check whether the form control name matches in both the html and typescript files

**Comment by ashsepra** [comment]
same with me, your name function same with your variable or model name. Just change one of it, it's work now.

**Comment by badgamerbad** [comment]
@sandeep2701kumar thanks for the fix, even if a portion of the function name matches with a variable name present in the same form, causes this issue.

**Comment by Booshna-Arthy** [comment]
> @sandeep2701kumar had same name of my function as the template name, thanks 👍

Thanks for your comment. i too made this mistake

**Comment by renanaribeiro** [comment]
Same happened to me. 
My backend users _login_ field as e-mail, changing declaration name on form page solved the issue.

**Comment by dm-grinko** [comment]
that was my reason:
```
        <mat-menu #delete="matMenu">
            <button mat-menu-item *ngFor="let item of items" (click)="delete(param)">{{param.title}}</button>
        </mat-menu>
```

**Comment by devxkuldeepchopra** [comment]
i got this issue here is some image clear my issue and this is how i fixed.

![image](https://user-images.githubusercontent.com/38593513/92328658-e911eb80-f07f-11ea-90d8-724dbf25692b.png)

![image](https://user-images.githubusercontent.com/38593513/92328644-d992a280-f07f-11ea-8443-f74887db8648.png)

![image](https://user-images.githubusercontent.com/38593513/92328671-fe871580-f07f-11ea-9f8a-440766df5780.png)
